#!/bin/bash
#1-store
if [ ! -n "$WORKSPACE_ROOT" ]; then
    echo "If you store for a cloned repo you may declare a WORKSPACE_ROOT environment variable before running this"
    exit 0
fi
cd $WORKSPACE_ROOT
if [ -z "${CRYPTOKEN}" ]; then
    echo "CRYPTOKEN is empty: $CRYPTOKEN"
    exit -1
fi
tar -cvJf _sensitive_datas/_sensitive_datas.tar.xz \
    apps/cloudflare-worker/.wrangler apps/cloudflare-worker/.vscode/launch.json apps/cloudflare-worker/.vscode/settings.json \
    apps/backend-admin/.vscode/launch.json apps/backend-admin/.vscode/settings.json \
    ./launch-* .env ios/.env ios/ParaWavePTT/.env
#2-encrypt
openssl aes-256-cbc -base64 -md sha256 -pass pass:"$CRYPTOKEN" -in _sensitive_datas/_sensitive_datas.tar.xz -out _sensitive_datas/_sensitive_datas.tar.xz.enc
#3-delete 
rm _sensitive_datas/_sensitive_datas.tar.xz

echo "CRYPTED with 'openssl aes-256-cbc -base64 -md sha256 -pass pass:\"$CRYPTOKEN\"'"